### ISSUE TITLE
Scope scherp formuleren

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#10]
N.a.v. eerste werksessie scope (hoofdstuk 2) iets anders geformuleerd. Graag reviewen.

**Comment by NieneB** [comment]
Zijn deze onderwerpen die in de inleiding genoemd worden niet deel van de scope?

> 
> De Prakrijktrichtlijn heeft tot doel om te specificeren hoe het beste vector tiles aangeboden kunnen worden om breed gebruik ervan mogelijk te maken, voor Nederlandse toepassingen.
> 
> Verschillen in de praktijk gelijk trekken zodat men vector tiles van verschillende aanbieders kan combineren.
> 
> Aanbod uniform = goede client kunnen bouwen. Zodat het makkelijker wordt vector tiles te gebruiken. Dit helpt bij het stimuleren gebruik Vector-tiling.
> 
> Makkelijker hergebruik vector tiles.

**Comment by NieneB** [comment]
Doelgroep beter formulieren? Is die iid onderdeel van de doelgroep ?

> - software leverancies van vector tiling software
