### ISSUE TITLE
H 4.3: High resolution tiles

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#15]
We gaan nu uit van 256 pixels. Of willen we juist 512 of 1024 voor Retina schermen als default? Mapbox heeft 512 als default, fallback 256.

Wat vindt de groep?

**Comment by thijsbrentjens** [comment]
512 als default en 256 (via resampling) als alternatief?

**Comment by arbakker** [comment]
High resolution vector tiles bestaan in principe niet. Standaard bevat een tegel een coordinatenspace van 4096x4096 eenheden (zie de [protobuf](https://github.com/mapbox/vector-tile-spec/blob/b87a6a16abc3fcda9ea3f0a68264b40f48e039f3/2.1/vector_tile.proto#L70).

Nu is het zo dat als we tegels kleiner maken (dus 256 X z_resolutie t.o.v 512 z_resolutie) dat er dan meer tegels zijn in totaal, en dus de informatie dichtheid toeneemt. Dus dan zou kleinere tegels "meer HD" zijn.

Tile size is verder ook een balans vinden in efficiëntie, kleinere tegels betekent ook meer overhead en meer dubbele features in de tegels. Met kleinere tegels heb je immers meer overlappende buffers. Ik was in de veronderstelling dat MapBox standaard tegels gebruikt van 512 groot, maar kan zo snel geen referentie vinden.

**Comment by thijsbrentjens** [comment]
opmerking maken bij TileMatrxiset dat daar 256 staat, maar dat dat vooral voor raster tiles van belang is. 

Voor vector tiles: opnemen in best practices, maar dan wel 512 x 512 pixels, sluit beter aan bij praktijk Mapbx en ESRI

**Comment by thijsbrentjens** [comment]
1. opmerking dat resolutie tilematrixset (256) niet voor de vector tiles geldt -> @thijsbrentjens 
1. best practices aanbeveling om 512x512 te gebruiken -> @thijsbrentjens
