### ISSUE TITLE
H 3.2 Encoding expliciet maken of niet?

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#17]
Encoding van data is nu een aparte eis bij het maken van Tiles, maar is dat wel nodig als Mapbox VT wordt voorgeschreven?

**Comment by arbakker** [comment]
Dat lijkt me niet nodig, dit wordt indd al voorgeschreven in de MVT spec. Zie https://docs.mapbox.com/vector-tiles/specification/#format

**Comment by thijsbrentjens** [comment]
Besproken in 2e sessie:
- OGC API Tiles noemt geen encoding
- inderdaad technisch niet nodig om op te nemen, maar voor duidelijkheid wel doen.

**Comment by NieneB** [comment]
encoding opgenomen als sub kopje netzoals de winding order. 
Ook bestands extensie uitzondering op de MVT spec toegevoegd voor de duidelijkheid
