### ISSUE TITLE
Linkje toevoegen naar website met praktijkrichtlijn

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#19]
Het zou handig zijn als er een linkje naar https://geonovum.github.io/praktijkrichtlijn-vector-tiling/ wordt opgenomen in de `about` van het repository. Zie bijv:

![Schermafbeelding 2020-12-09 093250](https://user-images.githubusercontent.com/3216462/101604692-925ed980-3a01-11eb-8507-5f22290bce59.png)

**Comment by thijsbrentjens** [comment]
gedaan
