### ISSUE TITLE
H 6 Tile Description (meta data) aanleveren, voorschrijven of niet?

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#2]
TileJson gebruiken of niet? Wat doet OGC API Tiles?

Details als iets over TileJson wordt beschreven: hoe omgaan met Tile json overzooming?

**Comment by NieneB** [comment]
TileJson is een van de encodings waarin je de Tile Description zou kunnen aanleveren

**Comment by NieneB** [comment]
- Data layers description and zoom levels
- Bounding box Tile set
- Attribution 
- Tile resource urls

**Comment by thijsbrentjens** [comment]
In hoeverre dekt OGC API Tiles dit?

**Comment by NieneB** [comment]
OGC API tiles heeft een endpoint /tiles waar de tegel set bron wordt beschreven. Samen met de TileMatrixSet definitie beschrijft dit de bron. 

> Vector` Tiles description | `/collections/{collectionId}/tiles`

> This is a building block for the an OGC API that describes the TileSet resource and how to retrieve a tile from a tileset

> Defines the response of a TileSet GET request (but not the path or the link for the request). The response has two formats: tilejson and OGC json. The OGC json includes tilematrixset links, a central point (optional), a links to the URI template to individual tiles, and the geospatial data resources involved in the creation of the tiles (optional), and other metadata (including attribution; optional) Defines how to formulate a request for individual tiles and how the response will look like (success and failure)

uit : https://htmlpreview.github.io/?https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.html#_conventions

1.Is de OGC API tiles endpoint voldoende voor de metadata beschrijving? 

2. Of eis voor tilejson spec van Mapbox voorschrijven? 

OGC API tiles geeft in de bijlage *Annex B* een draft voorbeeld voor TileJSON 3 
> The draft schema for TileJSON 3.0.0 is presented below for reference.

**Comment by NieneB** [comment]
Het ideaal is OGC API tiles te gebruiken. Daar zit al in de Core de bron beschrijving en meta data in. 
Tot die tijd lever een TileJSON bestand bij je tegel set zoals beschreven in Annex B van OGC API Tiles document

**Comment by NieneB** [comment]
Overzooming noemen als voordeel van tilejson

**Comment by NieneB** [comment]
1. Aanbeveling doen rondom format attribution?

**Comment by thijsbrentjens** [comment]
Besproken:
- aanbevelingen kunnen blijven staan (wel wat beter verwoorden), dus ook OGC API Tiles en TileJson
- attribution: goed om daar ook duidelijkheid over verschaffen
