### ISSUE TITLE
H3 na kijken

### ISSUE THREAD

**Issue by NieneB** [Geonovum/praktijkrichtlijn-vector-tiling#20]
In H4 wordt de OGC API Tiles benoemd die pas in H5 wordt benoemd als eis. Deze dus eerder als eis opnemen om het gehele  verhaal in het doc beter te laten lopen.

**Comment by NieneB** [comment]
H3 veranderen naar basis standaarden als aanbeveling.
Titel voorstel: 

-  **H3 Basis specificaties**
-  **H3 Te gebruiken specificaties**
- **H3 Uitgangspunten**

**Comment by NieneB** [comment]
H 3 hernoemd en kopjes beter opgesplitst. 

- [ ] review op links en referenties? 
- [ ] moet de ogc api tiles wat verder beschreven/ geintroduceerd worden hier?

**Comment by thijsbrentjens** [comment]
Ik vind het, buiten een paar hele kleine tekstuele zaken, goed zo
