### ISSUE TITLE
Opmerkingen bij CSRachtergrond.md

### ISSUE THREAD

**Issue by anneb** [Geonovum/praktijkrichtlijn-vector-tiling#28]
Tekst:
"Voor het maken van vector tiles zullen geometriëen omgerekend worden naar het lokale stelsel van een vector tile, in integers (vaak in een bereik van 0-4096 bij 0-4096). Dit betekent dat de originele geometrie nauwkeurigheid verliest in een vector tile." 

Vector tiles kunnen zeer nauwkeurig zijn, namelijk door verder in te zoomen en tiles op te vragen met een grotere zoom coördinaat. Bij het inzoomen beschrijven de tiles van 4096x4096 integers een steeds kleiner stukje wereld. Wanneer bijvoorbeeld een tile wordt opgevraagd die een stukje wereld van 1000x1000 meter bevat, dan zijn er per meter 4096/1000=4 integers beschikbaar. 1 integer heeft dan een nauwkeurigheid van 0.25 meter en dat is al een grotere nauwkeurigheid dan de beschreven tektonische verschuiving van 0.8 meter. Als je verder inzoomt, wordt de nauwkeurigheid nog groter.

Bij weergave-toepassingen is het vooral belangrijk dat elementen uit verschillende kaartlagen en bronnen goed op elkaar aansluiten. Het is dus van belang dat voor alle bronnen ofwel dezelfde CRS wordt gebruikt ofwel dat er CRSsen worden gebruikt waartussen openbaar toegankelijke transformaties beschikbaar zijn.

Tekst: 
"Het verschil tussen WGS84 en ETRS89 is daardoor opgelopen tot ruim 0,8 m in 2020."
is niet zo duidelijk. Dat zou bij het combineren dus kaarten opleveren waarop je duidelijk dubbele lijnen zou zien? Als dat gebeurt, dan betekent dat toch dat de toegepaste transformatieparameters tussen de beide CRS-sen verkeerd zijn? Er zijn toch transformaties beschikbaar waarbij je het jaar kunt opgeven waarvoor de WGS84 data is vastgelegd? Dat levert dan resultaten met een nauwkeurigheid van minimaal de gemiddelde jaarlijkse tektonische verschuiving (2.5 cm)?

**Comment by thijsbrentjens** [comment]
Dit lijkt me eentje waar @Jochem-L zinnige dingen over kan zeggen :) .

**Comment by thijsbrentjens** [comment]
We hebben voor de scope wel wat afgebakend over nauwkeurigheid. https://docs.geostandaarden.nl/serv/vt/#binnen-scope

Maar je hebt wel een punt dat, als je grootschalige toepassingen hebt, er verschillen kunnen gaan ontstaan. In termen van de "oude" (maar wel nog laatste) versie van de Praktijkrichtlijn tiling (WMTS) https://www.geonovum.nl/uploads/standards/downloads/nederlandse_richtlijn_tiling_-_versie_1.1.pdf , kom je op "schalen" uit van ongeveer 1:750 / 1:1500 waar dit met deze resoluties optreedt. Moeten we hier iets meer aandacht aan besteden?

**Comment by Jochem-L** [comment]
@anneb, Er zijn inderdaad nauwkeurige transformaties tussen ETRS89 en WGS84. Deze wordt echter in praktijk echter nog zelden gebruikt. Hiervoor zijn twee redenen:
* Om te kunnen bepalen welke transformatie tussen ETRS89 en WGS84 uitgevoerd moet worden, is het noodzakelijk de realisatie van beide CRS-en te specificeren (bijvoorbeeld ETRF2000 en WGS84-G1762). Hiervoor moeten een dan dus andere EPSG-codes gebruikt worden dan de veel gebruikte ensemble-codes EPSG:4258 en EPSG:4326 die naar de gehele verzameling van ETRS89- en WGS84-realisaties verwijzen. Zonder specificatie van de realisatie zal de meeste software een nul-transformatie toepassen.
* Om de juiste transformatie vervolgens ook toe te passen, zal er een epoche (tijdstip in de vorm van een decimaal jaartal met cijfers achter de komma) gespecificeerd moeten worden. In veel transformatiesoftware kan dat niet, en wordt er een willekeurig referentie-epoche (bijvoorbeeld 2010.0) gebruikt. Bovendien kunnen de meeste gebruikers en (GIS)software software er ook niet mee overweg dat coördinaten door de tijd heen veranderen.

Als gevolg daarvan worden ETRS89 en WGS84 meestal aan elkaar gelijk gesteld. Dit leidt tot nu toe meestal niet tot problemen aangezien geo-informatie in WGS84 meestal toch onnauwkeurig is en nauwkeurige geo-informatie eigenlijk altijd in ETRS89 ingewonnen wordt. Pas als gebruikers nauwkeurige WGS84-coördinaten inmeten (dat kan binnenkort iedereen met de Galileo High-Accuracy Service) of als gebruikers ETRS89 met de nauwkeurige tijdsafhankelijke transformatie naar WGS84 transformeren (omdat ze mij gevraagd hebben hoe dat moet) worden de verschillen van >0,8 m zichtbaar. 

Om de te verwachten toekomstige problemen hiermee te voorkomen zijn duidelijke richtlijnen en voorlichting nodig.

**Comment by arbakker** [comment]
@thijsbrentjens  berekenen nauwkeurigheid vector tile geometrie op zoomniveau 12:

- [resolutie z12](https://www.geonovum.nl/uploads/standards/downloads/nederlandse_richtlijn_tiling_-_versie_1.1.pdf): 0.84 m/pixel
- tilesize pixels: 256
- tilesize z12 meters: 256*0.84 = 215.04 m
- interne [vector tile extent](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers): 4096*4096
- nauwkeurigheid geometrien in mvt (als gevolg van inherente simplifcatie in mvt format):  215.04/4096 = 0.0525 m

nauwkeurigheid geometrien = (256 * resolution_z)/4096

**Comment by thijsbrentjens** [comment]
Dank, ik ga het verwerken. Voor de nauwkeurigheid ben ik nog een rekenvoorbeeld aan het toevoegen, over WebMercator. Als dat in de werkversie gepubliceerd is, vind ik een review wel handig

**Comment by thijsbrentjens** [comment]
Geen commentaar ontvangen, gepubliceerd
