### ISSUE TITLE
Opmerking bij best practices 2.1 wanneer vector tiles

### ISSUE THREAD

**Issue by anneb** [Geonovum/praktijkrichtlijn-vector-tiling#29]
Sommige van de hieronder opgesomde redenen om vector tiles te gebruiken zijn ook van toepassing op andere vector data zoals bijvoorbeeld vectordata uit WFS of geojson. WFS en geojson hebben echter als belangrijk nadeel dat ze ofwel langzaam ofwel omvangrijk kunnen zijn waardoor problemen met datatransport en geheugen kunnen ontstaan. Het toepassen van tiles voor vector data lost de problemen van trage services of omvangrijke bestanden grotendeels op.

Een aantal redenen om vector tiles te gebruiken:
* werken met omvangrijke vectordatasets
  * alleen downloaden wat je nodig hebt
  * minder geheugengebruik
  * snellere weergave met minder rekentijd
* met vector (-tiles) wordt de weergave bepaald door de weergavetoepassing 
  * selecteren en filteren van weer te geven data
  * instellen van render parameters (kleur, lijndikte, transparantie, symbolen etc.) bij de data
  * selecteren van weer te geven attributen, instellen klassificaties
  * instellen tekenvolgorde
  * on-the-fly koppelen met externe attribuut-data
* met vector (-tiles) is de data aan de client-zijde beschikbaar voor meer interactieve toepassingen
  * instantaan opvragen van data bij kaart-elementen
  * interactief oplichten van elementen
  * editen of verwijderen van elementen (=wegfilteren bronelement + toevoegen editable element)
  * interactief filteren of selecteren van elementen
* met vector (-tiles) kun je traploos zoomen 
* vector tiles zijn meestal compacter dan raster
  * minder data versturen tussen client en server
  * minder opslagruimte op server
* vector tiles zijn zeer geschikt voor grootschalige toepassingen (hoge zoomlevels)
  * mogelijkheid van overzooming (viewer verder ingezoomd dan zoomlevel van bron-tile)
  * gedetailleerde tiles hoeven vanwege mogelijkheid overzoomen niet gegenereerd te worden
    * bespaart rekentijd bij het voorbereiden van de data
    * bespaart datatransport via het netwerk
    * bespaart opslagruimte op de server
    * door minder data meer efficiënt gebruik van caches
* meer?

Redenen om geen vector tiles te gebruiken
* weinig vector data (alles past in 1 bestand of in 1 download)
* de brongegevens zijn rasterdata (foto's, dtms, andere data-rasters)
* geen kennis, behoefte of tijd om eigen kaart-weergaves te maken
  * (nog) geen standaardmethoden beschikbaar styles voor het renderen van vector uit te wisselen
* er worden primitieve clients gebruikt die geen vector data kunnen renderen
* het kost meer werk om gedetailleerde data te aggregeren voor kleinschalig (=lage zoomlevels) gebruik
* meer?

**Comment by thijsbrentjens** [comment]
Verplaatst naar https://github.com/Geonovum/vector-tiling-best-practices/issues/1
