### ISSUE TITLE
H 5.3 MBTiles en/of geopackage voor bulk download

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#3]
Een van beide formaten voorschrijven of allebei?

**Comment by thijsbrentjens** [comment]
Dat is: _als_ bulk download van tiles wordt aangeboden

**Comment by thijsbrentjens** [comment]
In gebruik zijn opslaan in een folder structure/directory, MBtiles (link naar spec) en geopackage (link naar spec). Wij raden aan om Geopackage (OGC specificatie) te gebruiken.

**Comment by NieneB** [comment]
https://github.com/mapbox/mbtiles-spec

**Comment by thijsbrentjens** [comment]
http://www.geopackage.org/spec121/#tiles

**Comment by NieneB** [comment]
https://www.geopackage.org/extensions.html

**Comment by thijsbrentjens** [comment]
Gaat om Community Extensions voor Vector Tiles. Welke daarvan te gebruiken? Is er ervaring mee en/of zijn er voorkeuren?

**Comment by skinkie** [comment]
Een daadwerkelijke evaluatie van "geopackage" (omvang) ten opzichte van MBTiles is gewenst. Niet "omdat het een OGC standaard is" is het - in die vorm - de "beste" uitwisselingsmethode.

**Comment by thijsbrentjens** [comment]
- naam veranderen: in download (zonder bulk)
- doel: download, hergebruik in andere tools en/of voor offline gebruik
- gemengde ervaringen: MBTiles, GeoPackage maar ook eenvoudige ZIP van tiles in directorystructuur -> geen hele duidelijke keuze te maken nu
- OGC API Tiles lijkt niets voor te schrijven

Conclusie: noemen dat er meerdere opties zijn, daarbij laten. Geen specifieke eis/aanbeveling opnemen, wel paragraaf laten staan omdat dit relevant is.
