### ISSUE TITLE
Onduidelijkheid omtrent het begrip "Vector tiles schema"

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#30]
Persoonlijk ben ik niet bekend met het begrip "vector tile schema". Wordt [hier](https://docs.geostandaarden.nl/serv/vt/#x4-vector-tiles-schema) met Vector tile schema eigenlijk niet TileMatrixSets bedoeld? Misschien beter om dan de kop _4. TileMatrixSet_ te gebruiken?

Een snelle [Google search](https://www.google.com/search?q=%22Vector+tiles+schema%22) leert dat het begrip vooral gebruikt wordt het schema van de data in de vector tiles aan te duiden (lagen en attributen in een vector tile)

En nog een klein detail in de tweede alinea van [4.1 Coördinaat Referentie Systemen](https://docs.geostandaarden.nl/serv/vt/#x4-1-coordinaat-referentie-systemen):

> Afhankelijk van de toepassing kan dit zeer ongewenste effecten hebben. 

Voorstel om kwaliticatie _zeer_ te verwijderen, zeer ongewenst is ook ongewenst (maar andersom niet noodzakelijkerwijs).

**Comment by thijsbrentjens** [comment]
Klopt, zijn TileMatrixSets en dat is misschien een betere term, omdat die in de (OGC) specs gebruikt wordt die de basis vormen.

**Comment by thijsbrentjens** [comment]
Verwerkt in werkversie
