### ISSUE TITLE
Voorstel: alinea over interne indeling vector tile elders plaatsen

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#31]
Alinea over interne indeling vector tile valt onder sectie [A.3 Impact onnauwkeurigheid WGS84 gering voor beoogde vector tiling toepassingen](https://docs.geostandaarden.nl/serv/vt/#a-3-impact-onnauwkeurigheid-wgs84-gering-voor-beoogde-vector-tiling-toepassingen), maar de onnauwkeurigheid van een vector tile als het gevolg van het interne coordinatenstelsel van 4096x4096 heeft niets te maken met de onnauwkeurigheid van WGS84. M.i.  vertroebelt dit de discussie over nauwkeurigheid van vt's. 

Daarom voorstel deze alinea elders in het document onder te brengen.

Gaat specifiek om deze alinea:

> Voor het maken van vector tiles zullen geometriëen omgerekend worden naar het lokale stelsel van een vector tile, in integers (vaak in een bereik van 0-4096 bij 0-4096). Dit betekent dat de originele geometrie nauwkeurigheid verliest in een vector tile.

Wellicht kan deze alinea ergen in [3. Basis specificaties](https://docs.geostandaarden.nl/serv/vt/#x3-basis-specificaties).

**Comment by thijsbrentjens** [comment]
De bijlage is veranderd, tekst aangepast, hopelijk daarmee dit ook opgelost.
