### ISSUE TITLE
vraag: waarom extensie en mime-type vrijgelaten?

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#32]
Waarom is de extensie en mimetype vrijgelaten, zie [3.2.1 Eis: Vrije Bestands Extensie](https://docs.geostandaarden.nl/serv/vt/#x3-2-1-eis-vrije-bestands-extensie)? Ik kan me de discussie hierover niet meer herinneren. 

Zou het niet beter zijn voor de interoperabiliteit dit wel voor te schrijven? 

Overigens lijkt me dit geen _EIS_, aangezien het vrij in te vullen is. Is eerder een absentie van een _EIS_

**Comment by arbakker** [comment]
voorstel: opmerking betreffende [mimetype ](https://docs.geostandaarden.nl/serv/vt/#x3-2-1-eis-vrije-bestands-extensie) verplaatsen naar [3.3 Vector tiles aanbieden](https://docs.geostandaarden.nl/serv/vt/#x3-3-vector-tiles-aanbieden) aangezien mimetype alleen relevant is bij het transport over het internet (en geen intrinsieke eigenschap van het vt betand zelf, zoals de bestandsextensie)

**Comment by arbakker** [comment]
Zie https://github.com/mapbox/vector-tile-spec/tree/master/2.1#21-file-extension

**Comment by thijsbrentjens** [comment]
Eerder in #17 discussie over gehad. De eis op zich is geen eis, maar geeft juist meer ruimte om een bestandsextensie te kiezen. Dit is in strijd met de spec van Mapbox.

En nu niet meer duidelijk waarom deze opgenomen is destijds, m.a.w.: wat voegt de eis nu toe? 

Misschien weet @NieneB meer?

**Comment by thijsbrentjens** [comment]
Over MIME-TYPE: als aanbeveling opnemen om het MIME-TYPE van mvt te gebruiken

**Comment by thijsbrentjens** [comment]
Zie ook #40

**Comment by thijsbrentjens** [comment]
Geen commentaar ontvangen, gepubliceerd
