### ISSUE TITLE
voorstel: sectie 3.3 onderbrengen hoofdstuk 5 (Vector tiles aanbieden)

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#34]
Er zijn twee onderdelen met het onderwerp _Vector tiles aanbieden_ .Voorstel om sectie [3.3 Vector tiles aanbieden](https://docs.geostandaarden.nl/serv/vt/#x3-3-vector-tiles-aanbieden) onder te brengen in [5. Vector tiles aanbieden](https://docs.geostandaarden.nl/serv/vt/#x5-vector-tiles-aanbieden).

**Comment by thijsbrentjens** [comment]
Hoofdstuk 3 benoemt de basisspecs, de hoofdstukken daarna werken dat uit. Dat wordt pas duidelijk in de laatste zin van hst 3. Ik voeg in de inleiding tekst toe om dat toe te lichten.

**Comment by arbakker** [comment]
Dat onderscheid was mij niet duidelijk, met deze aanpassing geen bezwaren.
