### ISSUE TITLE
discussie: resolutie is wel van toepassing op vector tiles

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#35]
Statement in [4.2 Eis: te gebruiken TileMatrixSets](https://docs.geostandaarden.nl/serv/vt/#x4-2-eis-te-gebruiken-tilematrixsets) is niet correct:

> Let op, de resolutie in de TileMatrixSet is niet van toepassing op vector tiles.

In het document [OGC Two Dimensional Tile Matrix Set](https://docs.opengeospatial.org/is/17-083r2/17-083r2.html) wordt de afmetingen van een tegel in "echte" wereld als volgt berekend: 

``` 
pixelSpan = scaleDenominator×0.28 10-3 / metersPerUnit(crs);
tileSpanX = tileWidth×pixelSpan;
tileSpanY = tileHeight×pixelSpan;
```

Zie hier bijvoorbeeld het verschil tussen grootte van tegels op Z1 van het rd tile grid bij een tileWidth,tileHeight=256 vs tileWidth,tileHeight=512. 

![image](https://user-images.githubusercontent.com/3216462/119150802-0f7d8880-ba4f-11eb-91ab-d386acf0de97.png)

Dit geldt voorzowel raster als vector tiles. Dus de resolutie/scaleDenominator is wel degelijke van toepassing op de afmetingen van de vector tiles. 

Het is wel zo dat deze resolutie niet direct de resolutie vertegenwoordigt van de geometrieen die in de vector tiles geencodeerd zijn (maar er is wel een relatie, aangezien tileSize van 256x256 weer opgedeeld is in een 4096 discrete eenheden).

**Comment by thijsbrentjens** [comment]
Zin schrappen, roept eerder meer vragen op dan dat het verduidelijkt.
