### ISSUE TITLE
discussie: eis publicatie van gebruikte CRS overbodig

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#36]
De [4.3 Eis: Publicatie van gebruikte CRS](https://docs.geostandaarden.nl/serv/vt/#x4-3-eis-publicatie-van-gebruikte-crs) lijkt me overbodig, omdat dit al wordt voorgeschreven door de [OGC API Tiles](http://docs.ogc.org/DRAFTS/20-057.html#table_resources). Voorstel om deze eis laten vallen, of motiveren waarom dit toch belangrijk genoeg is om toch extra voor te schrijven.

**Comment by thijsbrentjens** [comment]
Alleen de zin:

> Als vector tiles via OGC API Tiles worden aangeboden, is de TileMatrixSetId onderdeel van de URL en beschrijving van de vector tiles. Daarmee is het gebruikte CRS gepubliceerd.

naar 4.2 halen, de eis kan verder weg
