### ISSUE TITLE
voorstel: van aanbeveling content-encoding eis maken

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#37]
Voorstel om van [5.3 Aanbeveling: gebruik HTTP Header Content-Encoding bij gzip compressie op de webserver](https://docs.geostandaarden.nl/serv/vt/#x5-3-aanbeveling-gebruik-http-header-content-encoding-bij-gzip-compressie-op-de-webserver) een eis te maken. 

OpenLayers kan er bijvoorbeeld niet mee omgaan als de `Content-Encoding: gzip` header niet is toegevoegd. Ik verwacht dat er nog meer clients zijn die hier op stuk lopen.

**Comment by thijsbrentjens** [comment]
Overeengekomen: het is een eis, conditioneel

Korte toelichting waarom en opmerken dat sommige clients hierdoor niet werken.

**Comment by thijsbrentjens** [comment]
Voorbeeld request header maken. Titel inkorten.
