### ISSUE TITLE
voorstel: onnauwkeurigheid WGS84 in 1 sectie behandelen

### ISSUE THREAD

**Issue by arbakker** [Geonovum/praktijkrichtlijn-vector-tiling#39]
Duplicatie informatie in secties [4.1 Coördinaat Referentie Systemen](https://docs.geostandaarden.nl/serv/vt/#x4-1-coordinaat-referentie-systemen) 
en [A.3 Impact onnauwkeurigheid WGS84 gering voor beoogde vector tiling toepassingen](https://docs.geostandaarden.nl/serv/vt/#a-3-impact-onnauwkeurigheid-wgs84-gering-voor-beoogde-vector-tiling-toepassingen). In beide secties is de onnauwkeurigheid van WGS84 onderwerp.  Voorstel om dit in 1 sectie te behandelen.

**Comment by thijsbrentjens** [comment]
We hebben wel een stuk nodig over CRSen in hoofdstuk 4. Dus dat moet blijven staan. De bijlage is de verdieping, dit is niet zo zeer onderdeel van de specs, maar meer als extra uitleg. Daarom in een bijlage. Ik vind het zelf wel prettig dat de bijlage zelfstandig leesbaar is.

@arbakker vind je deze overlap storend / (te) onhandig?

**Comment by arbakker** [comment]
Goed punt, en bij nader inzien ook goed om vanuit hoofdstuk  4 wel te refereren aan dit onderwerp (onnauwkeurigheid CRS) in de bijlage.
