### ISSUE TITLE
Tekstueel: tiles, tegels of allebei?

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#4]
Welke term gebruiken? vector tiles, tegels of allebei door elkaar

**Comment by thijsbrentjens** [comment]
Kiezen voor "vector tiles" en "vector tiling"

**Comment by Jochem-L** [comment]
Als je er voor kiest een woord zoals "tile" in een Nederlandstalige richtlijn te gebruiken in plaats van "tegel", dan geef je daarmee impliciet aan dit als vakterm de voorkeur heeft in het Nederlands? 

Moet je het dan behandelen als een Engels woord in de tekst en dus steeds cursief schrijven en samenstellingen met Nederlandse woorden vermijden? Bijvoorbeeld: 
* Deze richtlijn voor _vector tiles_ wordt gepubliceerd in 2021. / <strike>Deze vector<i>tile</i>richtlijn wordt gepubliceerd in 2021.</strike>
* Het gebruik van _high-resolution tiles_ heeft de voorkeur. / Het gebruik van _tiles_ met hoge resolutie heeft de voorkeur.
* enz.
  
Of moet je het dan gebruiken als een leenwoord en dus grammaticaal gebruiken als een Nederlands woord en dus samenstellingen ook aan elkaar schrijven? Bijvoorbeeld: 
* Deze richtlijn voor vectortiles wordt gepubliceerd in 2021. / Deze vectortilerichtlijn wordt gepubliceerd in 2021.
* Het gebruik van hogeresolutietiles heeft de voorkeur. / Het gebruik van tiles met hoge resolutie heeft de voorkeur.
* enz.

**Comment by thijsbrentjens** [comment]
- [ ] Nederlands/Engelse samenstellingen voorkomen (voorstel Jochem overnemen)
- [ ] gebruik vector tiles, niet cursief

**Comment by Jochem-L** [comment]
Vector is een Nederlands woord, dus vector tiles is een Engels-Nederlandse samenstelling die dus ook vermeden moet worden?

**Comment by NieneB** [comment]
In de praktijk wordt er vaak gewerkt met Engelse termen. Dus ik denk dat de Engelse vorm vaker wordt gebruikt:  _vector tiles_ . (en niet _vectortiles_ of _vectortegels_  )

Los _tiles_ wordt echter niet vaak gebruikt. Ik merk dat ik dan toch snel _tegels_ gebruik. Doen we dat dan wel?
