### ISSUE TITLE
H 7 : OGC API Styles aanbevelen of niet

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#5]
willen we aansluiten bij OGC API Styles? 

Zie ook

https://ogc-vtp.gospatial.org/ogc-api-tiles/collections

https://www.youtube.com/watch?v=uGo5hYUwFP0

**Comment by NieneB** [comment]
- [ ] Uitzoeken OGC API styles

**Comment by NieneB** [comment]
**Resources:**

- https://www.ogc.org/projects/groups/stylesapiswg 
- https://ogcapi.ogc.org/styles/
- https://app.swaggerhub.com/apis/cportele/opf-style-api/1.0.0

> conceptual model for style encodings and style metadata.
> to support style sharing 
> the API provides a uniform means to publish and offer those styles as resources for use by other systems.
> The Styles API will allow for discovery, access, and application of multiple style resources 

* **Encodings**: supporting style resources in multiple style encodings (e.g., SLD, CSS, Mapbox Styles) 
 In Testbed-15 Mapbox Styles, OGC SLD versions 1.0 and 1.1 are used.

**Comment by thijsbrentjens** [comment]
vraag aan werkgroep: wordt het een eis/aanbeveling (best practice?): 
als je styling info wilt delen, doe het dan via OGC API Styles

**Comment by NieneB** [comment]
1. Moet je een stijl mee leveren bij een vt set?
2. Stijl aanbieden dmv OGC API styles?
3. Encoding : Mapbox Style spec als aanbeveling ?

**Comment by thijsbrentjens** [comment]
Besproken:
ad 1. aanbeveling doen om standaard stijl mee te leveren, want handig voor hergebruik
ad 2. nieuw, maar wel zinnig om te doen. Aanbeveling doen
ad 3. aanbevelen Mapbox style spec kan wel, die style spec wordt namelijk ook ondersteund in veel tooling

**Comment by thijsbrentjens** [comment]
Eerst #23 doen
