### ISSUE TITLE
H 4. (4.1, 4.1.1, 4.2) Publicatie van gebruikte CRS

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#7]
Uitwerken hoe je publiceert welk CRS de tiles hebben. Check ook OGC API Tiles.

**Comment by thijsbrentjens** [comment]
Als het geen WebMercator is, maak dan bekend in de API metadata (of in de URL?) welk CRS gebruikt is. Bijvoorbeeld in de TileJSON of in de API docs van OGC API Tiles.

In OGC API TIles is er een mechanisme voor. En zijn de volgende tilematrixsets bekend:

https://docs.opengeospatial.org/is/17-083r2/17-083r2.html

JSON encoding van deze tilematrixsets: http://schemas.opengis.net/tms/1.0/json/examples/

**Comment by thijsbrentjens** [comment]
OGC API Tiles doc: https://htmlpreview.github.io/?https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.html

**Comment by thijsbrentjens** [comment]
Lijkt erop dat TileJSON geen andere CRSen ondersteunt, dus kan nu alleen via OGC API Tiles bekend maken

**Comment by thijsbrentjens** [comment]
OGC API Tiles: URL bevat de `TileMatrixSetId`. 

Vraag: moeten we voor RD een `TileMatrixSetId` aanmaken? En een beschrijving maken?

**Comment by NieneB** [comment]
> CRS is opgenomen als tilematrixsetId in de resource url van de vector tile set:

Vector tile (geospatial resources1) | `/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}`

**Comment by thijsbrentjens** [comment]
Zie ook Example 2 in https://htmlpreview.github.io/?https://github.com/opengeospatial/OGC-API-Tiles/blob/master/core/standard/OAPI_Tiles.html: 

```
{
  "tileMatrixSetLink":
    {
      "tileMatrixSet": "WorldMercatorWGS84Quad",
      "tileMatrixSetURI": "http://schemas.opengis.net/tms/1.0/json/examples/WorldMercatorWGS84Quad.json"
    },
  ...
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
   }
   ...
  ]
}

```

**Comment by NieneB** [comment]
http://schemas.opengis.net/tms/1.0/json/examples/WorldMercatorWGS84Quad.json

**Comment by thijsbrentjens** [comment]
@NieneB maakt het json-bestand

@thijsbrentjens  beschrijft hoe dit op te nemen in praktijkrichtlijnen

**Comment by NieneB** [comment]
Identifier: "NetherlandsRDNewQuad"

**Comment by thijsbrentjens** [comment]
Voor WebMeractor: google maps compatible, want meeste toepassingen dan te gebruiken: http://schemas.opengis.net/tms/1.0/json/examples/WebMercatorQuad.json

**Comment by NieneB** [comment]
Van http://schemas.opengis.net/tms/ 

> TileMatrixSet specifies the concept of a tile matrix set and tile matrix set
> limits and its implementation in 2D space. This standard also provides both a
> XML and a JSON encoding. The Tile Matrix Set concept, initially developed in
> OGC Web Map Tile Service (WMTS) 1.0, is now provided as an independent standard
> that can be referenced by other standards such as WMTS 2.0 and GeoPackage, or
> the NRCan promoted standard candidate Map Markup Language (MapML). In addition,
> we ensure that the tile matrix set concept can be used by grid based tiles as
> well as for vector tiles.

**Comment by NieneB** [comment]
- [ ] Specifiveren TileMatrixSet conform http://schemas.opengis.net/tms/1.0/json/tms-schema.json voor het Rijksdriehoekstelsel

- [ ] Ook aanleveren XML format?

**Comment by NieneB** [comment]
https://geodata.nationaalgeoregister.nl/tiles/service/tms/1.0.0/brtachtergrondkaart/EPSG:28992 
https://www.geonovum.nl/uploads/standards/downloads/nederlandse_richtlijn_tiling_-_versie_1.1.pdf

**Comment by NieneB** [comment]
Zoom levels tot 14 of ook 15 en 16 ?

**Comment by thijsbrentjens** [comment]
Tot 16 maar doen? Het is misschien heel weinig gebruikt, maar het kan ook weer geen kwaad om extra zoomniveaus gedefinieerd te hebben

**Comment by thijsbrentjens** [comment]
Je hoeft geen data aan te bieden tot dat niveau, toch?

**Comment by thijsbrentjens** [comment]
Over XML format: kunnen we voorleggen aan de werkgroep. Maar ik zou zeggen dat we nu alleen een JSON format doen, sluit beter aan bij de APIs denk ik.

**Comment by NieneB** [comment]
Documenten in tekst als bijlage meenemen

**Comment by thijsbrentjens** [comment]
Er komen nog wat aanscherpingen van de tekst. @Jochem-L doet wat voorstellen.

Goed om ook verschuiving van WGS84-ETRS89 door de tijd heen op te nemen (2,5 cm/jaar), zodat partijen een afgewogen keuze kunnen maken welk CRS te gebruiken.

Vragen over waarom van ETRS89 LAEA. Anders zou kunnen, maar ook opgenomen voor aansluiting bij INSPRE. Als afwijken daarvan, met onderbouwing komen, vanwege impact.

**Comment by thijsbrentjens** [comment]
Over RD TileMatrixSet: alle tiles zijn net in volledige meters, maar  xxxxx.92 meter, waarom? @thijsbrentjens gaat uitzoeken.

Kan te maken hebben met de resolutie die ooit in WMTS door OGC is gekozen en doorwerkt in tiling schema.

**Comment by Jochem-L** [comment]
Voorstel voor tekstwijzigingen:

4.1 Coördinaat Referentie-Systemen
[...]
<strike>Maar van coördinaten in WGS84 is bekend dat die op het Europees vasteland soms te grote afwijkingen kunnen vertonen. In Nederland is WGS84 niet nauwkeurig genoeg als de data gebruikt wordt bij toepassingen die nauwkeuriger dan 1 meter moeten zijn.</strike>
Door tektonische verschuiving van Europa veranderen coördinaten van punten in Nederland met 2,5 cm/jaar. Het verschil tussen WGS84 en ETRS89 is daardoor opgelopen tot ruim 0,8 m in 2020. WGS84 is daarom minder geschikt voor nauwkeurige toepassingen.
[...]
NOOT: Notitie over realisatie van WGS84 en Web Mercator
<strike>Er is niet één scherpe definitie van WGS84. Om nauwkeurig te zijn, is het nodig naar een specifieke realisatie van WGS84 te verwijzen.</strike>
WGS84 is wordt periodiek bijgesteld op basis van nieuwe metingen. Voor nauwkeurige eenduidige definitie van het CRS is het daarom nodig en specifieke realisatie van WGS84 te vermelden (bijvoorbeeld WGS84-G1762, EPSG:9057). Vanwege de tektonische verschuiving van Europa is het daarnaast nodig het tijdstip (epoche) van de geldigheid van de coördinaten te vermelden. Bij coördinaten die direct in WGS84 gemeten zijn (zoals met een niet-landmeetkundige GPS-ontvanger) is het epoche het tijdstip van de meting. Bij transformatie van RD/ETRS89 naar een WGS84-realisatie wordt impliciet een referentie-epoche gebruikt of moet de gebruiker een epoche opgeven. Wanneer geen specifieke WGS84-realisatie gespecificeerd wordt, dan wordt meestal een onnauwkeurige nul-transformatie tussen ETRS89 en WGS84 gebruikt.

**Comment by thijsbrentjens** [comment]
Over tilematrixset die eindigt op .92: niet kunnen achterhalen wat de exacte reden was, maar dit aanpassen zou bestaande implementaties van "raster tiles" (WMTS etc) niet te combineren maken met vector tiles.
