### ISSUE TITLE
A. Best practices onderwerpen uitwerken

### ISSUE THREAD

**Issue by thijsbrentjens** [Geonovum/praktijkrichtlijn-vector-tiling#8]
Meer toelichting / uitwerking bij best practices. Voor nu vooral verzamelen van onderwerpen die in Best practices doc kunnen komen

**Comment by NieneB** [comment]
- [ ] Clipping en buffering onder een kopje

**Comment by NieneB** [comment]
Tegel set Optimalisatie als hoofd thema met daaronder

- simplificatie
- bestandsgrootte

?

**Comment by thijsbrentjens** [comment]
CRS en onderliggend systeem: eruit, want Vector tiles gaat over visualisatie. Stuk over CRSen en nauwkeurig geometrie uitwisselen is ergens anders (bij geonovum docs) wel relevant.

**Comment by arbakker** [comment]
Mogelijk interessant om te linken naar https://github.com/mapbox/postgis-vt-util/. 

> A set of PostgreSQL functions that are useful when creating vector tile sources, either at the query stage in Mapbox Studio or in the earlier data preparation stages.

**Comment by Jochem-L** [comment]
Tekstsuggestie:

A.3 Aanbeveling: Clipping & buffering
AANBEVELING Aanbeveling doen rondom clipping, ook rekening houden met CRS <strike>(o.a. mogelijk issue van lange lijnen i.c.m. herprojectie)</strike>
Een rechte lijn in het ene CRS is een kromme lijn in een ander CRS. Voor nauwkeurige weergave en clipping is de aanbeveling daarom om lange lijnsegmenten te voorkomen door in het CRS van de brondata om de 200 m tussenpunten toe te voegen voordat de data getransformeerd wordt naar een ander CRS. Voor data met een onnauwkeurigheid van 1 m zijn lijnsegmenten tot 5 km acceptabel.

**Comment by thijsbrentjens** [comment]
Besproken:
- meer use cases opnemen van vector tiles
- vermijd bij uitwerking de details over gebruikte software, dat kan namelijk snel veranderen, vraagt dan ook bijhouden. Zuiverder om specifieke tools/software niet te noemen
- best practices in apart doc, maar wel goed naar verwijzen in eerste hoofdstuk en paragrafen waar relevant (#21)

**Comment by thijsbrentjens** [comment]
Over CRS: ook opnemen bij best pracatices dat het zinnig is om correctie grids te gebruiken. Voor nauwkeurige transformatie is dat meer relevant dan bijvoorbeeld welke set towgs parameters die gebruikt wordt

**Comment by thijsbrentjens** [comment]
- [ ] kan weg als #21 is gedaan, dan komen in aparte repo de issues voor best practices

**Comment by thijsbrentjens** [comment]
zie ook #29 voor use cases

**Comment by thijsbrentjens** [comment]
Sluiten, aparte repo en issue lijst voor best practices
